# -*- mode: ruby -*-
# vi: set ft=ruby :
# Define the base image for the VM
base_image = "eurolinux-vagrant/centos-stream-9" 
#base_image = "ubuntu/jammy64"
# Define memory, CPU, hostname, and IP for the VM
memory_size = 2048                         
cpu_count = 2 
host_name = "artifactory"
ip_address = "192.168.56.20"

Vagrant.configure("2") do |config|
  # artifactory server configuration
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.define "artifactory" do |artifactory|
    # Set VM properties
    artifactory.vm.box = base_image
    artifactory.vm.hostname = host_name
    artifactory.vm.network :private_network, ip: ip_address
    artifactory.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", memory_size]
      v.customize ["modifyvm", :id, "--name", host_name]
      v.customize ["modifyvm", :id, "--cpus", cpu_count]
    end

     # Pass IP address to the provisioner script
     config.vm.provision "file", source: "../utils/", destination: "/tmp"
     artifactory.vm.provision "shell", path: "./scripts/main.sh", args: [ip_address]
    
  end
end
