# -*- mode: ruby -*-
# vi: set ft=ruby :
# Define the base image for the VM
base_image = "eurolinux-vagrant/centos-stream-9" 
#base_image = "ubuntu/jammy64"
# Define memory, CPU, hostname, and IP for the VM
memory_size = 2048                         
cpu_count = 2 
host_name = "sonarqube"
ip_address = "192.168.56.30"

Vagrant.configure("2") do |config|
  # sonarqube server configuration
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.define "sonarqube" do |sonarqube|
    # Set VM properties
    sonarqube.vm.box = base_image
    sonarqube.vm.hostname = host_name
    sonarqube.vm.network :private_network, ip: ip_address
    sonarqube.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", memory_size]
      v.customize ["modifyvm", :id, "--name", host_name]
      v.customize ["modifyvm", :id, "--cpus", cpu_count]
    end

    config.vm.provision "file", source: "../utils", destination: "/tmp"
   
    sonarqube.vm.provision "shell", path: "./scripts/main.sh", args: [ip_address]
    
  end
end
