# -*- mode: ruby -*-
# vi: set ft=ruby :
# Define the base image for the VM
base_image = "eurolinux-vagrant/centos-stream-9" 
#base_image = "ubuntu/jammy64"
# Define memory, CPU, hostname, and IP for the VM
memory_size = 2048                         
cpu_count = 2 
host_name = "jcr"
ip_address = "192.168.56.22"

Vagrant.configure("2") do |config|
  # jcr server configuration
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.define "jcr" do |jcr|
    # Set VM properties
    jcr.vm.box = base_image
    jcr.vm.hostname = host_name
    jcr.vm.network :private_network, ip: ip_address
    jcr.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", memory_size]
      v.customize ["modifyvm", :id, "--name", host_name]
      v.customize ["modifyvm", :id, "--cpus", cpu_count]
    end

   
    # Copy the 'scripts' folder to the VM during provisioning
    config.vm.provision "file", source: "scripts", destination: "/tmp/scripts"

    # Provisioning with a script  so add args docker to provsion
    jcr.vm.provision "shell", path: "main.sh" , args: "code"
    
  end
end
