# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile for setting up a Jenkins server

base_image = "eurolinux-vagrant/centos-stream-9" 
#base_image = "ubuntu/jammy64"
# Define memory, CPU, hostname, and IP for the VM
memory_size = 2048                         
cpu_count = 2 
host_name = "jenkins"
ip_address = "192.168.56.12"

Vagrant.configure("2") do |config|
  # jenkins server configuration
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key=false

  config.vm.define "jenkins" do |jenkins|
    # Set VM properties
    jenkins.vm.box = base_image
    jenkins.vm.hostname = host_name
    jenkins.vm.network :private_network, ip: ip_address
    jenkins.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", memory_size]
      v.customize ["modifyvm", :id, "--name", host_name]
      v.customize ["modifyvm", :id, "--cpus", cpu_count]
    end

    # Pass IP address to the provisioner script
    config.vm.provision "file", source: "../utils/", destination: "/tmp"
    jenkins.vm.provision "shell", path: "./scripts/main.sh", args: [ip_address]
  end
end
