# -*- mode: ruby -*-
# vi: set ft=ruby :

# Define the base image for the VM
#base_image = "eurolinux-vagrant/centos-stream-9" 
base_image = "ubuntu/jammy64"
# Define memory, CPU, hostname, and IP for the VM
memory_size = 2048                         
cpu_count = 2 
host_name = "jenkins"
ip_address = "192.168.56.10"

Vagrant.configure("2") do |config|
  # jenkins server configuration
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.define "jenkins" do |jenkins|
    # Set VM properties
    jenkins.vm.box = base_image
    jenkins.vm.hostname = host_name
    jenkins.vm.network :private_network, ip: ip_address
    jenkins.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", memory_size]
      v.customize ["modifyvm", :id, "--name", host_name]
      v.customize ["modifyvm", :id, "--cpus", cpu_count]
    end

    # SSH Configuration
    # config.vm.provision "shell", inline: <<-SHELL
    #   sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
    #   service ssh restart
    # SHELL

    # Provisioning with a separate script
    #jenkins.vm.provision "shell", path: "jenkins_setup.sh"
    jenkins.vm.provision "shell", path: "install_jenkins_docker.sh"
    
  end
end
